import Head from 'next/head'
import About from '../components/About'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jagger-Welding ( Jagger d.o.o )</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       {/* === Hero section === */}
        <Hero />
       {/* === About section === */}
       <About />
      </main>
    </div>
  )
}
