import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jagger-Welding ( Jagger d.o.o )</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>This is next JS</h1>
      </main>
    </div>
  )
}
